# Generated by Django 3.0 on 2022-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrack', '0003_auto_20220330_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('details', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
